dist: bionic
language: php

services:
  - redis-server

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.2
  - 7.3
  - 7.4

env:
  matrix:
    - LARAVEL=^6.0
    - LARAVEL=^7.0

matrix:
  fast_finish: true
  allow_failures:
    - env: LARAVEL=^7.0

before_install:
  - phpenv config-rm xdebug.ini || true
  - printf "\n" | pecl install -f redis

install:
  - travis_retry composer require "illuminate/contracts=${LARAVEL}" --dev --prefer-dist --no-interaction --no-suggest

script:
  - vendor/bin/phpunit --verbose
